/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.time.LocalDateTime;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



import DAO.DAO_ChiTietHoaDon;
import DAO.DAO_HoaDon;
import DAO.DAO_NhanVien;
import DAO.ExcelFileExportForHoaDon;
import ENTITY.ChiTietHoaDon;
import ENTITY.HangBay;
import ENTITY.HoaDon;
import ENTITY.NhanVien;
import utilies.ExportPDF;
/**
 *
 * @author admin
 */
public class GUI_HoaDon extends javax.swing.JPanel {
	
	// bien table 
	String headCollum[] = new String[] { "Mã Hóa Đơn","Tên Khách Hàng", "Tên Nhân Viên","Mã Vé" ,"Tên Vé", "Số Lượng", "Đơn Giá", "Thành Tiền", };
	private DefaultTableModel modelCTHD = new DefaultTableModel(headCollum, 0);
	private NhanVien nv; 
	//dao 
	private DAO_ChiTietHoaDon dao_cthd = new DAO_ChiTietHoaDon(); 
	private DAO_HoaDon dao_HoaDon = new DAO_HoaDon(); 
//	private DAO_NhanVien dao_NhanVien = new DAO_NhanVien(); 
	
	//list 
	private ArrayList<ChiTietHoaDon> listChiTietHoaDon; 
	
	
	
    /**
     * Creates new form GUI_HoaDon
     */
    public GUI_HoaDon(NhanVien nv) {
    	this.nv = nv; 
    	listChiTietHoaDon = dao_cthd.getalltbChiTietHoaDon(); 
    	
        initComponents();
        
        duaDuLieuVaoModule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QLHĐ = new javax.swing.JPanel();
        CTHĐ = new javax.swing.JPanel();
        maHĐ = new javax.swing.JLabel();
        txtMaHĐ = new javax.swing.JTextField();
        maVeMayBay = new javax.swing.JLabel();
        txtMaVeMayBay = new javax.swing.JTextField();
        soGhe = new javax.swing.JLabel();
        txtSoGhe = new javax.swing.JTextField();
        donGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        thanhTien = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        timHĐ = new javax.swing.JLabel();
        txtTimHĐ = new javax.swing.JTextField();
        btnXuatHĐ = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textKhachHang = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangHD = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout QLHĐLayout = new javax.swing.GroupLayout(QLHĐ);
        QLHĐ.setLayout(QLHĐLayout);
        QLHĐLayout.setHorizontalGroup(
            QLHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        QLHĐLayout.setVerticalGroup(
            QLHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        maHĐ.setText("Mã hóa đơn");

        txtMaHĐ.setEditable(false);
        txtMaHĐ.setMinimumSize(new java.awt.Dimension(240, 30));
        txtMaHĐ.setPreferredSize(new java.awt.Dimension(240, 25));

        maVeMayBay.setText("Mã vé máy bay");

        txtMaVeMayBay.setMinimumSize(new java.awt.Dimension(240, 30));
        txtMaVeMayBay.setPreferredSize(new java.awt.Dimension(240, 25));

        soGhe.setText("Số Lượng");

        txtSoGhe.setMinimumSize(new java.awt.Dimension(240, 30));
        txtSoGhe.setPreferredSize(new java.awt.Dimension(240, 25));

        donGia.setText("Đơn giá");

        txtDonGia.setMinimumSize(new java.awt.Dimension(240, 30));
        txtDonGia.setPreferredSize(new java.awt.Dimension(240, 25));

        thanhTien.setText("Thành tiền");

        txtThanhTien.setMinimumSize(new java.awt.Dimension(240, 30));
        txtThanhTien.setPreferredSize(new java.awt.Dimension(240, 25));

        btnTimKiem.setBackground(new java.awt.Color(25, 145, 166));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        timHĐ.setText("Tìm theo SDT");

        txtTimHĐ.setPreferredSize(new java.awt.Dimension(240, 30));

        btnXuatHĐ.setBackground(new java.awt.Color(25, 145, 166));
        btnXuatHĐ.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnXuatHĐ.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatHĐ.setText("Xuất hóa đơn");
        btnXuatHĐ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHĐActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhân Viên");

        jLabel3.setText("Khách Hàng");

        javax.swing.GroupLayout CTHĐLayout = new javax.swing.GroupLayout(CTHĐ);
        CTHĐ.setLayout(CTHĐLayout);
        CTHĐLayout.setHorizontalGroup(
            CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTHĐLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CTHĐLayout.createSequentialGroup()
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timHĐ)
                            .addGroup(CTHĐLayout.createSequentialGroup()
                                .addComponent(txtTimHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CTHĐLayout.createSequentialGroup()
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CTHĐLayout.createSequentialGroup()
                                .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(donGia))
                                .addGap(276, 276, 276)
                                .addComponent(btnXuatHĐ))
                            .addGroup(CTHĐLayout.createSequentialGroup()
                                .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maVeMayBay))
                                .addGap(151, 151, 151)
                                .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(txtNhanVien)
                                        .addComponent(textKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CTHĐLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thanhTien)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maHĐ)
                        .addComponent(soGhe))
                    .addContainerGap(788, Short.MAX_VALUE)))
        );
        CTHĐLayout.setVerticalGroup(
            CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTHĐLayout.createSequentialGroup()
                .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CTHĐLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maVeMayBay)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaVeMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(txtNhanVien))
                        .addGap(18, 18, 18)
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donGia)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(timHĐ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(btnXuatHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CTHĐLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtMaHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(CTHĐLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CTHĐLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(maHĐ)
                    .addGap(59, 59, 59)
                    .addComponent(soGhe)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(thanhTien)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bangHD.setModel(modelCTHD);
        bangHD.setRowHeight(30);
        bangHD.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bangHDAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(bangHD);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 115, 135));
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN CHI TIẾT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QLHĐ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CTHĐ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CTHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
    	// Lấy số điện thoại từ trường nhập liệu
        String sdtKH = txtTimHĐ.getText().trim();
        
        // Kiểm tra số điện thoại không được để trống
        if (sdtKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại khách hàng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Gọi phương thức từ DAO để lấy danh sách chi tiết hóa đơn
        ArrayList<ChiTietHoaDon> listChiTietHoaDonTheoSDT = dao_cthd.getalltbChiTietHoaDonTheoSDT(sdtKH);
        
        // Kiểm tra nếu danh sách rỗng
        if (listChiTietHoaDonTheoSDT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn nào cho số điện thoại: " + sdtKH, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Xóa dữ liệu cũ trên bảng
        modelCTHD.setRowCount(0);

        // Duyệt qua danh sách và thêm dữ liệu vào bảng
        for (ChiTietHoaDon chiTietHoaDon : listChiTietHoaDonTheoSDT) {
            modelCTHD.addRow(new Object[] { 
                chiTietHoaDon.getMaHoaDon().getMaHoaDon(), 
                chiTietHoaDon.getMaHoaDon().getMaKhachHang().getHoTen(), 
                chiTietHoaDon.getMaNhanVien().getTenNhanVien(), 
                chiTietHoaDon.getMaVe().getMaVe(), 
                chiTietHoaDon.getMaVe().getMaHangBay().getTenHangBay(),
                chiTietHoaDon.getMaHoaDon().getSoLuong(), 
                chiTietHoaDon.getMaVe().getGia(), 
                chiTietHoaDon.getTongTien()
            });
        }

        // Hiển thị thông báo thành công
//        JOptionPane.showMessageDialog(this, "Đã tìm thấy " + listChiTietHoaDon.size() + " hóa đơn.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXuatHĐActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHĐActionPerformed
    	// Kiểm tra xem người dùng đã chọn dòng nào trong bảng chưa
        int selectedRow = bangHD.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để thực hiện.");
            return;
        }

        // Lấy giá trị maHoaDon và maVe từ các cột 0 và 3 của dòng được chọn
        String maHoaDon = bangHD.getValueAt(selectedRow, 0).toString();
        String maVe = bangHD.getValueAt(selectedRow, 3).toString();

        // Lấy thông tin ChiTietHoaDon từ dao_cthd
        ChiTietHoaDon cthd = dao_cthd.getOneObjChiTietHoaDon(maHoaDon, maVe, nv.getMaNhanVien());

        double tongTien = cthd.getTongTien();
        double number = 0; // Biến lưu số tiền khách nhập
        while (true) {
            String input = JOptionPane.showInputDialog("Nhập tiền khách đưa: ");

            try {
                // Chuyển đổi giá trị nhập vào thành double
                number = Double.parseDouble(input);

                // Kiểm tra nếu số tiền nhập vào hợp lệ (lớn hơn hoặc bằng tổng tiền)
                if (number < tongTien) {
                    JOptionPane.showMessageDialog(null, "Số tiền bạn nhập không đủ, vui lòng nhập lại.");
                } else {
                    // Tiến hành các thao tác nếu số tiền hợp lệ
                    JOptionPane.showMessageDialog(null, "Số tiền hợp lệ. Đang xử lý...");

                    // Xuất file Excel và hiển thị thông báo
                    ExcelFileExportForHoaDon excelFEFF = new ExcelFileExportForHoaDon(cthd, number, number - tongTien);
                    break;
                }

            } catch (NumberFormatException e) {
                // Xử lý khi người dùng nhập không phải là số thực hợp lệ
                JOptionPane.showMessageDialog(null, "Vui lòng nhập một số thực hợp lệ.");
            }
        }
		
    	
    }//GEN-LAST:event_btnXuatHĐActionPerformed

    private void bangHDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bangHDAncestorAdded
    	// TODO add your handling code here:
    			bangHD.getSelectionModel().addListSelectionListener(e -> {
    				// Kiểm tra xem có dòng nào được chọn không
    				int selectedRow = bangHD.getSelectedRow();
    				if (selectedRow != -1) {
    					
    					
    					// Lấy dữ liệu từ dòng được chọn
    					String maHD = bangHD.getValueAt(selectedRow, 0).toString();
    					HoaDon hd = dao_HoaDon.getOneObjHoaDon(maHD); 
    					String khachHang = bangHD.getValueAt(selectedRow, 1).toString();
    					String nhanVien = bangHD.getValueAt(selectedRow, 2).toString();
    					String tenHangBay = bangHD.getValueAt(selectedRow, 4).toString();
    					String soLuong = bangHD.getValueAt(selectedRow, 5).toString();
    					String donGia = bangHD.getValueAt(selectedRow, 6).toString();
    					String thanhTien = bangHD.getValueAt(selectedRow, 7).toString();
    					
    					// Gán dữ liệu vào các JTextField
//    					txtMaHB.setText(maHB);
//    					txtTenHB.setText(tenHB);
//    					txtQuocGia.setText(quocGia);
    					txtMaHĐ.setText(maHD); 
    					textKhachHang.setText(khachHang); 
    					txtNhanVien.setText(nhanVien);
    					txtMaVeMayBay.setText(tenHangBay); 
    					txtSoGhe.setText(soLuong); 
    				    txtDonGia.setText(donGia); 
    				    txtThanhTien.setText(thanhTien); 
    				    txtTimHĐ.setText(hd.getMaKhachHang().getSoDienThoai());
    					
    				}
    			});
    }//GEN-LAST:event_bangHDAncestorAdded
    
    public void duaDuLieuVaoModule() {
    	modelCTHD.setRowCount(0);
		for (ChiTietHoaDon chiTietHoaDon : listChiTietHoaDon) {
			modelCTHD.addRow(new Object[] { chiTietHoaDon.getMaHoaDon().getMaHoaDon(), chiTietHoaDon.getMaHoaDon().getMaKhachHang().getHoTen(), 
					chiTietHoaDon.getMaNhanVien().getTenNhanVien(),chiTietHoaDon.getMaVe().getMaVe() ,chiTietHoaDon.getMaVe().getMaHangBay().getTenHangBay(),
					chiTietHoaDon.getMaHoaDon().getSoLuong(), chiTietHoaDon.getMaVe().getGia(), chiTietHoaDon.getTongTien()});
		}
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CTHĐ;
    private javax.swing.JPanel QLHĐ;
    private javax.swing.JTable bangHD;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXuatHĐ;
    private javax.swing.JLabel donGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maHĐ;
    private javax.swing.JLabel maVeMayBay;
    private javax.swing.JLabel soGhe;
    private javax.swing.JTextField textKhachHang;
    private javax.swing.JLabel thanhTien;
    private javax.swing.JLabel timHĐ;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHĐ;
    private javax.swing.JTextField txtMaVeMayBay;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSoGhe;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimHĐ;
    // End of variables declaration//GEN-END:variables
}
