/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class GUI_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Thongke
     */
    private GUI_ThongKeTheoThoiGian guiThongKeTheoThoiGian;
    private GUI_ThongKeTheoThang guiThongKeTheoThang;
//    private GUI_ThongKeTheoQuy guiThongKeTheoQuy;
//    private GUI_ThongKeTheoNam guiThongKeTheoNam;
    private GUI_ThongKeTheoHangBay guiThongKeTheoHangBay;
    private GUI_ThongKeTheoChuyenBay guiThongKeTheoChuyenBay;
    public GUI_ThongKe() {
        guiThongKeTheoThoiGian = new GUI_ThongKeTheoThoiGian();
        guiThongKeTheoThang = new GUI_ThongKeTheoThang();
//        guiThongKeTheoQuy = new GUI_ThongKeTheoQuy();
//        guiThongKeTheoNam = new GUI_ThongKeTheoNam();
        guiThongKeTheoHangBay = new GUI_ThongKeTheoHangBay();
        guiThongKeTheoChuyenBay = new GUI_ThongKeTheoChuyenBay();
        initComponents();
        this.contentPanel.add(guiThongKeTheoThoiGian);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnThoiGian = new javax.swing.JButton();
        btnChuyenBay = new javax.swing.JButton();
        btnHangBay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1278, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        menuPanel.setBackground(new java.awt.Color(10, 90, 110));
        menuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        menuPanel.setPreferredSize(new java.awt.Dimension(1278, 109));

        btnThoiGian.setBackground(new java.awt.Color(0, 147, 166));
        btnThoiGian.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnThoiGian.setForeground(new java.awt.Color(255, 255, 255));
        btnThoiGian.setText("Thời gian");
        btnThoiGian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiGianActionPerformed(evt);
            }
        });

        btnChuyenBay.setBackground(new java.awt.Color(0, 147, 166));
        btnChuyenBay.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnChuyenBay.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenBay.setText("Chuyến bay");
        btnChuyenBay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnChuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBayActionPerformed(evt);
            }
        });

        btnHangBay.setBackground(new java.awt.Color(0, 147, 166));
        btnHangBay.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHangBay.setForeground(new java.awt.Color(255, 255, 255));
        btnHangBay.setText("Hãng bay");
        btnHangBay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnHangBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangBayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setText("THỐNG KÊ DOANH THU");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnHangBay, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHangBay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiGianActionPerformed
        // TODO add your handling code here:
        switchPanel(contentPanel, guiThongKeTheoThoiGian);
    }//GEN-LAST:event_btnThoiGianActionPerformed

    private void btnChuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBayActionPerformed
        // TODO add your handling code here:
        switchPanel(contentPanel, guiThongKeTheoChuyenBay);
    }//GEN-LAST:event_btnChuyenBayActionPerformed

    private void btnHangBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangBayActionPerformed
        // TODO add your handling code here:
        switchPanel(contentPanel, guiThongKeTheoHangBay);
    }//GEN-LAST:event_btnHangBayActionPerformed

private static void switchPanel(JPanel contentPanel, JPanel newPanel) {
        contentPanel.removeAll(); // Xóa tất cả các thành phần cũ
        contentPanel.setLayout(new BorderLayout()); // Đảm bảo sử dụng BorderLayout
        contentPanel.add(newPanel, BorderLayout.CENTER); // Thêm JPanel mới vào trung tâm
        contentPanel.revalidate(); // Làm mới bố cục
        contentPanel.repaint(); // Vẽ lại giao diện
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenBay;
    private javax.swing.JButton btnHangBay;
    private javax.swing.JButton btnThoiGian;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
