/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.*;
import java.time.ZonedDateTime;

import DAO.*;
import ENTITY.*;

/**
 *
 * @author ADMIN
 */
public class GUI_ThongKeTheoNgay extends javax.swing.JPanel {

    /**
     * Creates new form GUI_HangBay
     */
	// DAO
		private DAO_KhachHang dao_kh = new DAO_KhachHang();
		private DAO_HoaDon dao_hd = new DAO_HoaDon();
		private DAO_ChiTietHoaDon dao_cthd = new DAO_ChiTietHoaDon();

	// LIST
		private ArrayList<KhachHang> listKH;
		private ArrayList<HoaDon> listHD;
		private ArrayList<ChiTietHoaDon> listCTHD;
		
		private DefaultTableModel modeltable = new DefaultTableModel();
    public GUI_ThongKeTheoNgay() {
    	listKH = dao_kh.getalltbKhachHang();
		listHD = dao_hd.getalltbHoaDon();
		listCTHD = dao_cthd.getalltbChiTietHoaDon();
        initComponents();
        
        modeltable = (DefaultTableModel) tableThongKeTheoNgay.getModel();
        duaDuLieuVaoModule();
        Tong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKeTheoNgay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        DateChooserThongKeTheoNgay = new com.toedter.calendar.JDateChooser();
        btnHienThi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableThongKeTheoNgay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày lập hóa đơn", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tableThongKeTheoNgay);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 90, 110));
        jLabel1.setText("Tổng doanh thu: ");

        btnHienThi.setBackground(new java.awt.Color(10, 90, 110));
        btnHienThi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHienThi.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThi.setText("Hiển thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 90, 110));
        jLabel2.setText("Thống kê theo ngày");

        jLabel3.setText("Chọn ngày:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateChooserThongKeTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(278, 278, 278))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateChooserThongKeTheoNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btnHienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

//    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
//        // TODO add your handling code here:
//        Date selectedDate = DateChooserThongKeTheoNgay.getDate();
//                if (selectedDate != null) {
//
//                	// Xóa tất cả các dòng trong bảng
//            		modeltable.setRowCount(0);
//
//            		boolean coKetQua = false; // Cờ để kiểm tra có kết quả hay không
//
//            		for (ChiTietHoaDon cthd : listCTHD) {
//            			if(selectedDate.toLocalDate().equals())
//            				// Thêm dữ liệu vào bảng
//            				modeltable.addRow(new Object[] { cthd.getMaHoaDon().getMaHoaDon(), cthd.getNgayLapHoaDon(),
//            						cthd.getMaHoaDon().getSoLuong(), cthd.getTongTien() });
//
//            				coKetQua = true; // Có ít nhất một kết quả phù hợp
//            			}
//            		}
//                
//         }
//GEN-LAST:event_btnHienThiActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {
        Date selectedDate = DateChooserThongKeTheoNgay.getDate();
        if (selectedDate != null) {
            // Chuyển đổi Date từ JDateChooser thành LocalDate
            LocalDate selectedLocalDate = selectedDate.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            // Xóa tất cả các dòng trong bảng
            modeltable.setRowCount(0);

            // Biến cờ kiểm tra kết quả
            boolean coKetQua = false;
            double tongDoanhThu = 0;

            // Duyệt qua danh sách ChiTietHoaDon
            for (ChiTietHoaDon cthd : listCTHD) {
                // Giả sử getNgayLapHoaDon trả về LocalDate
            	LocalDateTime ngayLapHoaDonDateTime = cthd.getNgayLapHoaDon(); // Lấy giá trị trả về là LocalDateTime
            	LocalDate ngayLapHoaDon = ngayLapHoaDonDateTime.toLocalDate();

                // So sánh ngày
                if (selectedLocalDate.equals(ngayLapHoaDon)) {
                    // Thêm dữ liệu vào bảng
                    modeltable.addRow(new Object[]{
                            cthd.getMaHoaDon().getMaHoaDon(),
                            ngayLapHoaDon,
                            cthd.getMaHoaDon().getSoLuong(),
                            cthd.getTongTien()
                    });

                    // Tính tổng doanh thu
                    tongDoanhThu += cthd.getTongTien();

                    coKetQua = true; // Có ít nhất một kết quả phù hợp
                }
            }

            // Hiển thị thông báo nếu không có kết quả
            if (!coKetQua) {
                JOptionPane.showMessageDialog(this, "Không có dữ liệu cho ngày được chọn.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }

            // Hiển thị tổng doanh thu
            DecimalFormat x = new DecimalFormat("###,###,###");
            jLabel1.setText("Tổng doanh thu: " + x.format(tongDoanhThu) + " VNĐ");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày để hiển thị.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    
public void duaDuLieuVaoModule() {
	for (ChiTietHoaDon cthd : listCTHD) {
		modeltable.addRow(new Object[] { 
				cthd.getMaHoaDon().getMaHoaDon(), 
				cthd.getNgayLapHoaDon(),
				cthd.getMaHoaDon().getSoLuong(),
				cthd.getTongTien() });
		}
	}
    
public void Tong() {
	DecimalFormat x = new DecimalFormat("###,###,###");
	double sum = 0;
	for(int i = 0; i < modeltable.getRowCount(); i++) {
		sum += Double.parseDouble(modeltable.getValueAt(i, 3).toString());
	}
	
	jLabel1.setText("Tổng doanh thu: " + x.format(sum) + " VNĐ");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserThongKeTheoNgay;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThongKeTheoNgay;
    // End of variables declaration//GEN-END:variables
}
